CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE recipes (
    "ID" INTEGER NOT NULL,
    "NAME" TEXT NOT NULL,
    "FILEPATH" TEXT
);
CREATE UNIQUE INDEX "RECIPES_IDX_ID" on recipes (ID ASC);
CREATE TABLE "users" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "USERNAME" TEXT NOT NULL
);
CREATE INDEX "USERS_IDX_ID" on users (ID ASC);
CREATE TABLE categories (
    "ID" INTEGER NOT NULL,
    "NAME" TEXT NOT NULL DEFAULT ('unassigned'),
    "USER_ID" INTEGER NOT NULL
);
CREATE TABLE "categories_details" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "CATEGORY_ID" INTEGER NOT NULL,
    "RECIPE_ID" INTEGER NOT NULL
);
