CREATE TABLE "CATEGORIES_DETAILS" (
  "ID"          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "CATEGORY_ID" INTEGER                           NOT NULL,
  "RECIPE_ID"   INTEGER                           NOT NULL
  ,
  USER_ID       INTEGER
);
CREATE TABLE sqlite_sequence(name, seq);
CREATE TABLE CATEGORIES (
  "ID"      INTEGER,
  "NAME"    TEXT    NOT NULL DEFAULT ('unassigned'),
  "USER_ID" INTEGER NOT NULL
);
CREATE TABLE USERS (
  "ID"       INTEGER,
  "USERNAME" TEXT,
  "EMAIL"    TEXT,
  "PASSWORD" TEXT
);
CREATE INDEX "USERS_IDX_ID"
  ON users (ID ASC);
CREATE TABLE RECIPES (
  "ID"       INTEGER NOT NULL,
  "NAME"     TEXT    NOT NULL,
  "FILEPATH" TEXT,
  "OWNERID"  INTEGER NOT NULL DEFAULT (0)
);
CREATE UNIQUE INDEX "RECIPES_IDX_ID" on recipes (ID ASC);
